services:
  db:
    image: mysql:8.0
    restart: always
    command: '--query_cache_type=0 --query_cache_size=0'
    environment:
      MYSQL_ROOT_PASSWORD: 'strongpassword'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
